minimum_pre_commit_version: "3.2.2"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
        args: ["--unsafe"]
      - id: end-of-file-fixer
      - id: no-commit-to-branch
      - id: trailing-whitespace

  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format  # toml formatter
        args: ["--option","align_comments=false","--option","indent_string=    ", "--option","column_width=100"]
        exclude: ^playground/

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.36.0
    hooks:
      - id: check-github-workflows
      - id: check-github-actions

  - repo: https://github.com/hukkin/mdformat
    rev: 1.0.0
    hooks:
    - id: mdformat  # markdown formatter
      additional_dependencies:
      - mdformat-black
      - mdformat-pyproject
      - mdformat-simple-breaks
      exclude: ^(playground/|documentation/license\.md)

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
      - id: ruff
        args: [--fix]
        exclude: ^playground/
      - id: ruff-format
        exclude: ^playground/
