from beanie import Document
from pydantic import BaseModel, Field
from app.core.config import settings
from beanie import PydanticObjectId

from utils.random_name import random_chat_name

class Group(Document):
    # group id is autogenerated by beanie
    user_id: PydanticObjectId
    name: str = Field(default_factory=random_chat_name)

    class Settings:
        name = settings.GROUP_COLLECTION_NAME
        indexes = ["user_id", [("last_updated", -1)]]
