from beanie import Document
from typing import Optional

from app.core.config import settings
from beanie import PydanticObjectId

class Video(Document):
    # video_id is autogenerated by beanie
    user_id: PydanticObjectId
    group_id: PydanticObjectId
    run_id: Optional[PydanticObjectId] = None

    name: str = ""
    length: int = 0
    thumbnail: str = ""
    url: str = ""

    ingested_status: float = 0 # 0 -100: not ingested, 100: ingested
    @property 
    def ingested(self) -> bool:
        return self.ingested_status >= 100

    class Settings:
        name = settings.VIDEO_COLLECTION_NAME
        indexes = ["user_id", [("last_updated", -1)]]
